Repository Ignite-Discord/Ignite, pull requests merged in 2021-09, with the labels that each got.

#1 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#2 Update trivia.txt
  trivia.txt
Labels: enhancement

#3 Update trivia.txt
  trivia.txt
Labels: enhancement

#4 Update README.md
  README.md
Labels: documentation, enhancement, good first issue

#5 Update prefix in footer & activity
  src/main/java/com/general_hello/commands/Bot.java
Labels: fix grammar
